package tool.automator.executor.constants;

public enum ParserErrorConst {
	NO_ERRORS,
	INVALID_LINE_TYPE,
	INVALID_COMMAND_TYPE,
	INVALID_VALIDATION_STATEMENT_FORMAT,
	INVALID_EXECUTION_STATEMENT_FORMAT,
	INAVALID_DIRECTIVE_STATEMENT_FORMAT
}
