+START_MODULE
	+START_STEP
		+START_GLOBAL
			$PROJECT = Air-Canada
			$RELEASE = 60
			$BROWSER = Firefox
		+END_GLOBAL
	+END_STEP
	+START_STEP
		+START_CASE
			$PAGE = Home-Page[1]
			$FLOW_TYPE = Fare-Driven
			$MARKET_TYPE = Domestic
			$NUMBER_OF_BOUNDS = 1
			$TRIP_TYPE = One-Way
			$ROUTE = YUL-YYC
			$ORIGIN[1] = YUL
			$DESTINATION[1] = YYC
			$TRAVEL_DATE_1 = 05/11/2011
			$NUMBER_OF_PASSENGERS = 1
			$ADULT-YOUTH-CHILD-INFANT = 1-0-0-0
			@SELECT_PASSENGERS = CALL
			$USER_TYPE = Guest
			$RESIDENCE_COUNTRY = Canada
			$SEARCH_SUBMIT = CLICK
		+END_CASE
	+END_STEP
	+START_STEP
		+START_CASE
			$PAGE == Availability[1]
			$EUPGRAGE_FLOW = FALSE
			$CHANGE_DATE = FALSE
			$FARE_FAMILY[1] = Tango-Plus
			$NUMBER_OF_SEGMENTS[1] = 1
			$FLIGHT_CODE[1] = ANY
			@SELECT_FLIGHT[1] = CALL
			$CONTINUE = CLICK
		+END_CASE
	+END_STEP
	+START_STEP
		+START_CASE
			$PAGE == Discount[1]
			$CONTINUE = CLICK
		+END_CASE
	+END_STEP
	+START_STEP
		+START_CASE
			$PAGE == Fare-Review[1]
			$QUOTE_DETAILS = CLICK
			$ACCEPT = CLICK
		+END_CASE
	+END_STEP
	+START_STEP
		+START_CASE
			$PAGE == Login[1]
			$CONTINUE = CLICK
		+END_CASE
	+END_STEP
	+START_STEP
		+START_CASE
			$PAGE == Passenger-Information[1]
			$TITLE[1] = Mr
			$FIRST_NAME[1] = TestFirstName
			$NAME_INITIAL[1] = A
			$LAST_NAME[1] = TestLastName
			$SEAT_PREFERENCE[1] = Aisle
			$MOBILE_AREACODE = 123
			$MOBILE_NUMBER = 1234567
			$EMAIL_ID = test@test.com
			$CONTINUE = CLICK
		+END_CASE
	+END_STEP
	+START_STEP
		+START_CASE
			$PAGE == Purchase[1]
			$QUOTE_DETAILS = CLICK
			$CARD_TYPE = Visa
			$CARD_NUMBER = 4012999999999999
			$CARD_EXPIRY_MONTH = 01
			$CARD_EXPIRY_YEAR = 2015
			$CARD_NAME = TestFirstName TestLastName
			$ADDRESS_COUNTRY = Canada
			$ADDRESS_LINE1 = Test Line 1
			$ADDRESS_LINE2 = Test Line 2
			$ADDRESS_CITY = Test City
			$ADDRESS_PROVINCE = Alberta
			$ADDRESS_POSTALCODE = 123456
			$CONFIRM_EMAIL = test@test.com
			$PURCHASE = CLICK
		+END_CASE
	+END_STEP
	+START_STEP
		+START_CASE
			$PAGE == Seat-Selection[1]
			$SEAT_SELECT_FLOW = TRUE
			#$SKIP_SEAT_SELECTION = CLICK
			$SEAT_PREFERENCE[1] = Regular
			@SELECT_SEAT[1] = CALL
			$CONFIRM = CLICK
		+END_CASE
	+END_STEP
+END_MODULE