package tool.automator.executor.constants;

public enum WebDriverErrorConst {
	NO_ERRORS,
	BROWSER_NOT_SUPPORTED,
	COULD_NOT_CREATE_DRIVER,
	ELEMENT_NULL,
	COULD_NOT_FIND_ELEMENT_ON_PAGE,
	WRONG_ELEMENT_GET_TYPE,
	COULD_NOT_CLICK_ELEMENT,
	COULD_NOT_SET_VALUE,
	COULD_NOT_ENTER_VALUE,
	COULD_NOT_INPUT_VALUE,
	COULD_NOT_SELECT_VALUE,
	ELEMENT_TYPE_NOT_SUPPORTED,
	COULD_NOT_GET_ELEMENT_VALUE,
	COULD_NOT_CLOSE_DRIVER
}
